[package]
name = "ppl-framework-host"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
ppl-contracts = { path = "../../crates/contracts" }
ppl-aut-01 = { path = "../../components/aut-01" }
ppl-iam-01 = { path = "../../components/iam-01" }
ppl-int-01 = { path = "../../components/int-01" }
serde = "1"
serde_json = "1"
time = "0.3"

[lints]
workspace = true
