apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-scenario-director
  namespace: public-purpose-lab
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-presentation-gateway
  namespace: public-purpose-lab
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-identity-broker
  namespace: public-purpose-lab
  annotations:
    iam.gke.io/return-principal-id-as-email: "true"
automountServiceAccountToken: true
