apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-scenario-director
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-presentation-gateway
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: m3-identity-broker
  annotations:
    iam.gke.io/return-principal-id-as-email: "true"
automountServiceAccountToken: true
